[2024-02-27T03:55:33.220+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:55:33.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:55:33.222+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:55:33.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:55:33.224+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:55:33.227+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:55:33.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:55:33.228+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:55:33.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.026 seconds
[2024-02-27T03:56:03.983+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:56:03.983+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:56:03.985+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:56:03.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:56:03.986+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:56:03.987+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:56:03.986+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:56:03.988+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:56:04.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T03:56:34.292+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:56:34.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:56:34.294+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:56:34.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:56:34.296+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:56:34.297+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:56:34.296+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:56:34.298+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:56:34.311+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T03:57:04.665+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:57:04.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:57:04.667+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:57:04.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:57:04.668+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:57:04.670+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:57:04.669+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:57:04.671+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:57:04.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.024 seconds
[2024-02-27T03:57:35.034+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:57:35.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:57:35.036+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:57:35.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:57:35.038+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:57:35.039+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:57:35.038+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:57:35.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:57:35.055+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.024 seconds
[2024-02-27T03:58:05.397+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:58:05.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:58:05.399+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:58:05.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:58:05.401+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:58:05.402+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:58:05.401+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:58:05.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:58:05.418+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.023 seconds
[2024-02-27T03:58:35.788+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:58:35.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:58:35.790+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:58:35.789+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:58:35.791+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:58:35.793+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:58:35.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:58:35.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:58:35.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.024 seconds
[2024-02-27T03:59:06.155+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:59:06.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:59:06.157+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:59:06.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:59:06.158+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:59:06.160+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:59:06.159+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:59:06.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:59:06.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T03:59:36.601+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/resource.py
[2024-02-27T03:59:36.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T03:59:36.603+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:59:36.603+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T03:59:36.605+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T03:59:36.606+0000] {logging_mixin.py:188} INFO - [2024-02-27T03:59:36.605+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T03:59:36.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T03:59:36.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:00:06.968+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:00:06.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:00:06.970+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:00:06.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:00:06.971+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:00:06.973+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:00:06.972+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:00:06.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:00:06.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.023 seconds
[2024-02-27T04:00:37.296+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:00:37.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:00:37.299+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:00:37.298+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:00:37.301+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:00:37.303+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:00:37.301+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:00:37.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:00:37.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.028 seconds
[2024-02-27T04:01:07.817+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:01:07.818+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:01:07.819+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:01:07.819+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:01:07.822+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:01:07.825+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:01:07.822+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:01:07.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:01:07.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.031 seconds
[2024-02-27T04:01:38.265+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:01:38.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:01:38.267+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:01:38.267+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:01:38.270+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:01:38.272+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:01:38.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:01:38.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:01:38.290+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.027 seconds
[2024-02-27T04:02:08.600+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:02:08.601+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:02:08.602+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:02:08.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:02:08.604+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:02:08.606+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:02:08.604+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:02:08.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:02:08.621+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.024 seconds
[2024-02-27T04:02:38.932+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:02:38.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:02:38.934+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:02:38.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:02:38.936+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:02:38.937+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:02:38.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:02:38.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:02:38.952+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:03:09.267+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:03:09.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:03:09.269+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:03:09.269+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:03:09.271+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:03:09.273+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:03:09.272+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:03:09.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:03:09.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.024 seconds
[2024-02-27T04:03:39.647+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:03:39.648+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:03:39.649+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:03:39.649+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:03:39.651+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:03:39.652+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:03:39.651+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:03:39.653+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:03:39.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T04:04:09.992+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:04:09.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:04:09.994+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:04:09.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:04:09.996+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:04:09.998+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:04:09.996+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:04:09.998+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:04:10.012+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T04:04:40.364+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:04:40.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:04:40.366+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:04:40.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:04:40.367+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:04:40.368+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:04:40.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:04:40.369+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:04:40.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:05:10.698+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:05:10.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:05:10.700+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:05:10.700+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:05:10.701+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:05:10.703+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:05:10.702+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:05:10.703+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:05:10.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:05:41.058+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:05:41.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:05:41.060+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:05:41.060+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:05:41.063+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:05:41.065+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:05:41.063+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:05:41.065+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:05:41.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:06:11.417+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:06:11.418+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:06:11.419+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:06:11.419+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:06:11.421+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:06:11.423+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:06:11.421+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:06:11.423+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:06:11.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.023 seconds
[2024-02-27T04:06:41.825+0000] {processor.py:161} INFO - Started process (PID=303) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:06:41.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:06:41.826+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:06:41.826+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:06:41.828+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:06:41.829+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:06:41.828+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:06:41.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:06:41.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.023 seconds
[2024-02-27T04:07:12.223+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:07:12.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:07:12.225+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:07:12.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:07:12.227+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:07:12.229+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:07:12.227+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:07:12.229+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:07:12.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.022 seconds
[2024-02-27T04:07:42.558+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:07:42.558+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:07:42.559+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:07:42.559+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:07:42.561+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:07:42.562+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:07:42.561+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:07:42.563+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:07:42.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.020 seconds
[2024-02-27T04:08:12.918+0000] {processor.py:161} INFO - Started process (PID=339) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:08:12.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:08:12.921+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:08:12.920+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:08:12.923+0000] {logging_mixin.py:188} INFO - dag_id is not available. Skipping resource allocation.
[2024-02-27T04:08:12.925+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:08:12.924+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/resource.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/resource.py", line 24, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 498, in __init__
    validate_key(dag_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 53, in validate_key
    raise TypeError(f"The key has to be a string and is {type(k)}:{k}")
TypeError: The key has to be a string and is <class 'NoneType'>:None
[2024-02-27T04:08:12.926+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:08:12.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.029 seconds
[2024-02-27T04:08:38.305+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:08:38.306+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:08:38.308+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:08:38.307+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:08:38.309+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:08:38.309+0000] {dagbag.py:325} INFO - File /opt/airflow/dags/resource.py assumed to contain no DAGs. Skipping.
[2024-02-27T04:08:38.309+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:08:38.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.021 seconds
[2024-02-27T04:09:08.655+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:09:08.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:09:08.659+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:09:08.659+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:09:08.661+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:09:08.660+0000] {dagbag.py:325} INFO - File /opt/airflow/dags/resource.py assumed to contain no DAGs. Skipping.
[2024-02-27T04:09:08.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:09:08.672+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.019 seconds
[2024-02-27T04:09:39.021+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:09:39.022+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:09:39.024+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:09:39.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:09:39.025+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:09:39.025+0000] {dagbag.py:325} INFO - File /opt/airflow/dags/resource.py assumed to contain no DAGs. Skipping.
[2024-02-27T04:09:39.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:09:39.036+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.017 seconds
[2024-02-27T04:10:09.379+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/resource.py
[2024-02-27T04:10:09.381+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/resource.py for tasks to queue
[2024-02-27T04:10:09.382+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:10:09.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/resource.py
[2024-02-27T04:10:09.383+0000] {logging_mixin.py:188} INFO - [2024-02-27T04:10:09.383+0000] {dagbag.py:325} INFO - File /opt/airflow/dags/resource.py assumed to contain no DAGs. Skipping.
[2024-02-27T04:10:09.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/resource.py
[2024-02-27T04:10:09.393+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/resource.py took 0.016 seconds
