[2024-03-04T04:25:43.616+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:25:43.616+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:25:43.618+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:25:43.618+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:25:43.621+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:25:43.620+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:25:43.621+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:25:43.635+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T04:26:14.047+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:14.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:26:14.048+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:26:14.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:14.051+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:26:14.050+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:26:14.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:14.065+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:26:44.384+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:44.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:26:44.385+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:26:44.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:44.387+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:26:44.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:26:44.388+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:26:44.401+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:27:14.771+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:14.772+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:27:14.773+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:27:14.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:14.776+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:27:14.775+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:27:14.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:14.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T04:27:45.170+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:45.171+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:27:45.172+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:27:45.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:45.175+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:27:45.175+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:27:45.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:27:45.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:28:15.567+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:15.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:28:15.569+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:28:15.569+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:15.571+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:28:15.570+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:28:15.571+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:15.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:28:45.936+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:45.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:28:45.938+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:28:45.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:45.941+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:28:45.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:28:45.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:28:45.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T04:29:16.325+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:16.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:29:16.327+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:29:16.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:16.329+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:29:16.329+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:29:16.329+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:16.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-04T04:29:46.720+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:46.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:29:46.721+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:29:46.721+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:46.724+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:29:46.723+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:29:46.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:29:46.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:30:17.478+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:17.480+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:30:17.482+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:30:17.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:17.486+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:30:17.484+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:30:17.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:17.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.067 seconds
[2024-03-04T04:30:48.011+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:48.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:30:48.013+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:30:48.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:48.015+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:30:48.015+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:30:48.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:30:48.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:31:18.375+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:18.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:31:18.377+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:31:18.377+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:18.380+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:31:18.379+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:31:18.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:18.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:31:48.739+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:48.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:31:48.741+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:31:48.741+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:48.744+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:31:48.743+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:31:48.744+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:31:48.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:32:19.122+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:19.122+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:32:19.124+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:32:19.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:19.126+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:32:19.125+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:32:19.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:19.142+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:32:49.517+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:49.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:32:49.519+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:32:49.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:49.521+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:32:49.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:32:49.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:32:49.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:33:19.938+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:19.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:33:19.941+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:33:19.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:19.945+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:33:19.944+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:33:19.945+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:19.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-03-04T04:33:50.586+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:50.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:33:50.589+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:33:50.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:50.592+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:33:50.591+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:33:50.592+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:33:50.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-03-04T04:34:21.045+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:21.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:34:21.048+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:34:21.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:21.052+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:34:21.051+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:34:21.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:21.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.037 seconds
[2024-03-04T04:34:51.528+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:51.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:34:51.530+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:34:51.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:51.532+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:34:51.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:34:51.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:34:51.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:35:21.902+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:21.903+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:35:21.905+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:35:21.904+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:21.908+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:35:21.907+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:35:21.908+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:21.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T04:35:52.318+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:52.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:35:52.320+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:35:52.320+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:52.322+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:35:52.322+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:35:52.322+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:35:52.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-04T04:36:22.779+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:22.779+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:36:22.780+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:36:22.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:22.782+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:36:22.782+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:36:22.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:22.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-04T04:36:53.123+0000] {processor.py:161} INFO - Started process (PID=304) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:53.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:36:53.125+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:36:53.124+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:53.127+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:36:53.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:36:53.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:36:53.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:37:23.521+0000] {processor.py:161} INFO - Started process (PID=316) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:23.521+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:37:23.522+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:37:23.522+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:23.525+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:37:23.524+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:37:23.525+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:23.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:37:53.932+0000] {processor.py:161} INFO - Started process (PID=328) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:53.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:37:53.934+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:37:53.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:53.936+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:37:53.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:37:53.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:37:53.951+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:38:24.307+0000] {processor.py:161} INFO - Started process (PID=340) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:24.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:38:24.309+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:38:24.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:24.311+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:38:24.310+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:38:24.311+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:24.324+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:38:54.940+0000] {processor.py:161} INFO - Started process (PID=352) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:54.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:38:54.942+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:38:54.941+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:54.944+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:38:54.943+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:38:54.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:38:54.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T04:39:25.440+0000] {processor.py:161} INFO - Started process (PID=364) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:25.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:39:25.443+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:39:25.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:25.448+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:39:25.447+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:39:25.448+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:25.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.032 seconds
[2024-03-04T04:39:55.844+0000] {processor.py:161} INFO - Started process (PID=376) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:55.845+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:39:55.846+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:39:55.846+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:55.848+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:39:55.848+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:39:55.848+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:39:55.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T04:40:26.266+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:26.267+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:40:26.269+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:40:26.268+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:26.272+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:40:26.271+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:40:26.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:26.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-03-04T04:40:56.848+0000] {processor.py:161} INFO - Started process (PID=400) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:56.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:40:56.850+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:40:56.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:56.852+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:40:56.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:40:56.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:40:56.865+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T04:41:27.213+0000] {processor.py:161} INFO - Started process (PID=412) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:27.214+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:41:27.216+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:41:27.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:27.219+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:41:27.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:41:27.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:27.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.055 seconds
[2024-03-04T04:41:57.716+0000] {processor.py:161} INFO - Started process (PID=424) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:57.717+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:41:57.718+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:41:57.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:57.722+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:41:57.720+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:41:57.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:41:57.737+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T04:42:28.093+0000] {processor.py:161} INFO - Started process (PID=436) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:28.094+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:42:28.095+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:42:28.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:28.098+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:42:28.098+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:42:28.099+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:28.113+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T04:42:58.445+0000] {processor.py:161} INFO - Started process (PID=448) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:58.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:42:58.447+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:42:58.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:58.449+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:42:58.448+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:42:58.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:42:58.463+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:43:28.801+0000] {processor.py:161} INFO - Started process (PID=460) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:28.802+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:43:28.803+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:43:28.803+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:28.805+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:43:28.805+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:43:28.805+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:28.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:43:59.428+0000] {processor.py:161} INFO - Started process (PID=472) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:59.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:43:59.436+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:43:59.436+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:59.443+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:43:59.442+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:43:59.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:43:59.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.049 seconds
[2024-03-04T04:44:29.968+0000] {processor.py:161} INFO - Started process (PID=484) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:44:29.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:44:29.970+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:44:29.970+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:44:29.972+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:44:29.971+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:44:29.972+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:44:29.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:45:00.446+0000] {processor.py:161} INFO - Started process (PID=496) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:00.448+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:45:00.449+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:45:00.449+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:00.452+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:45:00.451+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:45:00.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:00.469+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-03-04T04:45:30.883+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:30.884+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:45:30.885+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:45:30.885+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:30.888+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:45:30.887+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:45:30.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:45:30.902+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:46:01.394+0000] {processor.py:161} INFO - Started process (PID=520) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:01.395+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:46:01.396+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:46:01.396+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:01.398+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:46:01.397+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:46:01.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:01.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:46:31.908+0000] {processor.py:161} INFO - Started process (PID=532) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:31.909+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:46:31.910+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:46:31.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:31.914+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:46:31.913+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:46:31.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:46:31.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T04:47:02.367+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:02.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:47:02.369+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:47:02.369+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:02.371+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:47:02.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:47:02.372+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:02.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:47:32.983+0000] {processor.py:161} INFO - Started process (PID=556) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:32.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:47:32.985+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:47:32.985+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:32.987+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:47:32.987+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:47:32.987+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:47:33.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T04:48:03.542+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:03.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:48:03.544+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:48:03.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:03.547+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:48:03.546+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:48:03.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:03.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-03-04T04:48:34.165+0000] {processor.py:161} INFO - Started process (PID=580) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:34.166+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:48:34.168+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:48:34.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:34.173+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:48:34.171+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:48:34.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:48:34.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.048 seconds
[2024-03-04T04:49:04.791+0000] {processor.py:161} INFO - Started process (PID=592) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:04.792+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:49:04.793+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:49:04.793+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:04.797+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:49:04.796+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:49:04.798+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:04.815+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-03-04T04:49:36.172+0000] {processor.py:161} INFO - Started process (PID=610) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:36.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:49:36.184+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:49:36.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:36.198+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:49:36.197+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:49:36.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:49:36.291+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.131 seconds
[2024-03-04T04:50:07.047+0000] {processor.py:161} INFO - Started process (PID=622) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:07.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:50:07.050+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:50:07.049+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:07.053+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:50:07.052+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:50:07.053+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:07.080+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.035 seconds
[2024-03-04T04:50:37.514+0000] {processor.py:161} INFO - Started process (PID=634) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:37.516+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:50:37.519+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:50:37.518+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:37.521+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:50:37.521+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:50:37.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:50:37.538+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-03-04T04:51:07.901+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:07.905+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:51:07.907+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:51:07.907+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:07.911+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:51:07.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:51:07.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:07.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-03-04T04:51:38.305+0000] {processor.py:161} INFO - Started process (PID=658) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:38.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:51:38.313+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:51:38.313+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:38.327+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:51:38.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:51:38.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:51:38.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.053 seconds
[2024-03-04T04:52:09.051+0000] {processor.py:161} INFO - Started process (PID=670) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:09.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:52:09.058+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:52:09.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:09.067+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:52:09.064+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:52:09.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:09.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.068 seconds
[2024-03-04T04:52:39.782+0000] {processor.py:161} INFO - Started process (PID=682) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:39.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:52:39.785+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:52:39.785+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:39.791+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:52:39.790+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:52:39.792+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:52:39.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.041 seconds
[2024-03-04T04:53:10.318+0000] {processor.py:161} INFO - Started process (PID=693) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:10.319+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:53:10.321+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:53:10.321+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:10.325+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:53:10.324+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:53:10.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:10.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-03-04T04:53:40.787+0000] {processor.py:161} INFO - Started process (PID=705) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:40.790+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:53:40.792+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:53:40.792+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:40.796+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:53:40.795+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:53:40.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:53:40.817+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.034 seconds
[2024-03-04T04:54:11.508+0000] {processor.py:161} INFO - Started process (PID=717) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:11.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:54:11.510+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:54:11.509+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:11.512+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:54:11.512+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:54:11.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:11.526+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T04:54:41.893+0000] {processor.py:161} INFO - Started process (PID=729) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:41.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:54:41.895+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:54:41.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:41.899+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:54:41.898+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:54:41.900+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:54:41.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.035 seconds
[2024-03-04T04:55:12.336+0000] {processor.py:161} INFO - Started process (PID=741) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:12.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:55:12.340+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:55:12.340+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:12.343+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:55:12.342+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:55:12.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:12.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T04:55:42.723+0000] {processor.py:161} INFO - Started process (PID=753) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:42.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:55:42.727+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:55:42.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:42.729+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:55:42.728+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:55:42.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:55:42.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.038 seconds
[2024-03-04T04:56:13.137+0000] {processor.py:161} INFO - Started process (PID=765) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:13.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:56:13.141+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:56:13.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:13.151+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:56:13.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:56:13.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:13.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.050 seconds
[2024-03-04T04:56:43.530+0000] {processor.py:161} INFO - Started process (PID=777) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:43.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:56:43.533+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:56:43.533+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:43.536+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:56:43.535+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:56:43.537+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:56:43.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.044 seconds
[2024-03-04T04:57:14.164+0000] {processor.py:161} INFO - Started process (PID=789) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:14.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:57:14.168+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:57:14.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:14.171+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:57:14.170+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:57:14.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:14.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T04:57:44.550+0000] {processor.py:161} INFO - Started process (PID=801) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:44.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:57:44.554+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:57:44.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:44.557+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:57:44.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:57:44.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:57:44.575+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-03-04T04:58:14.932+0000] {processor.py:161} INFO - Started process (PID=813) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:14.933+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:58:14.934+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:58:14.934+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:14.937+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:58:14.936+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:58:14.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:14.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-03-04T04:58:45.331+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:45.332+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:58:45.333+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:58:45.333+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:45.337+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:58:45.335+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:58:45.337+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:58:45.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T04:59:15.851+0000] {processor.py:161} INFO - Started process (PID=837) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:15.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:59:15.864+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:59:15.863+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:15.876+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:59:15.873+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:59:15.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:15.918+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.069 seconds
[2024-03-04T04:59:46.340+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:46.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T04:59:46.343+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:59:46.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:46.347+0000] {logging_mixin.py:188} INFO - [2024-03-04T04:59:46.346+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T04:59:46.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T04:59:46.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-03-04T05:00:16.687+0000] {processor.py:161} INFO - Started process (PID=861) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:16.688+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:00:16.690+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:00:16.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:16.693+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:00:16.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:00:16.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:16.708+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T05:00:47.109+0000] {processor.py:161} INFO - Started process (PID=872) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:47.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:00:47.113+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:00:47.112+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:47.116+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:00:47.115+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:00:47.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:00:47.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-03-04T05:01:17.526+0000] {processor.py:161} INFO - Started process (PID=884) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:17.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:01:17.529+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:01:17.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:17.532+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:01:17.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:01:17.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:17.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-03-04T05:01:47.898+0000] {processor.py:161} INFO - Started process (PID=896) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:47.900+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:01:47.902+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:01:47.901+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:47.904+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:01:47.904+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:01:47.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:01:47.922+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-03-04T05:02:18.610+0000] {processor.py:161} INFO - Started process (PID=908) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:18.618+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:02:18.619+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:02:18.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:18.622+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:02:18.621+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:02:18.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:18.638+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.030 seconds
[2024-03-04T05:02:48.968+0000] {processor.py:161} INFO - Started process (PID=920) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:48.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:02:48.972+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:02:48.972+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:48.976+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:02:48.975+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:02:48.976+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:02:48.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T05:03:19.607+0000] {processor.py:161} INFO - Started process (PID=932) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:19.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:03:19.611+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:03:19.611+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:19.614+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:03:19.613+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:03:19.614+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:19.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.046 seconds
[2024-03-04T05:03:50.369+0000] {processor.py:161} INFO - Started process (PID=945) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:50.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:03:50.376+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:03:50.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:50.380+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:03:50.379+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:03:50.380+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:03:50.411+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.046 seconds
[2024-03-04T05:04:20.875+0000] {processor.py:161} INFO - Started process (PID=957) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T05:04:20.876+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T05:04:20.878+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:04:20.877+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:04:20.885+0000] {logging_mixin.py:188} INFO - [2024-03-04T05:04:20.880+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T05:04:20.887+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T05:04:20.908+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.036 seconds
[2024-03-04T09:54:02.341+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:02.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:54:02.343+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:54:02.343+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:02.345+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:54:02.345+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:54:02.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:02.362+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T09:54:35.596+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:35.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:54:35.598+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:54:35.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:35.600+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:54:35.599+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:54:35.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:54:35.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T09:55:06.031+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:06.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:55:06.032+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:55:06.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:06.035+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:55:06.034+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:55:06.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:06.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T09:55:36.429+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:36.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:55:36.431+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:55:36.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:36.434+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:55:36.434+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:55:36.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:55:36.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T09:56:06.859+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:06.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:56:06.860+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:56:06.860+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:06.863+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:56:06.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:56:06.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:06.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T09:56:37.247+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:37.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:56:37.249+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:56:37.249+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:37.252+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:56:37.251+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:56:37.252+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:56:37.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T09:57:07.624+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:07.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:57:07.626+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:57:07.625+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:07.629+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:57:07.628+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:57:07.629+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:07.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T09:57:38.032+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:38.032+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:57:38.033+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:57:38.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:38.036+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:57:38.035+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:57:38.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:57:38.051+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T09:58:08.430+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:08.430+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:58:08.432+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:58:08.431+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:08.435+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:58:08.434+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:58:08.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:08.451+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T09:58:38.847+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:38.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:58:38.850+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:58:38.849+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:38.853+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:58:38.852+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:58:38.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:58:38.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T09:59:09.546+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:09.546+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:59:09.548+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:59:09.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:09.551+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:59:09.550+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:59:09.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:09.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T09:59:39.967+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:39.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T09:59:39.969+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:59:39.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:39.971+0000] {logging_mixin.py:188} INFO - [2024-03-04T09:59:39.971+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T09:59:39.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T09:59:39.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T10:00:10.370+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:10.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:00:10.372+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:00:10.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:10.374+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:00:10.373+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:00:10.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:10.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T10:00:40.773+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:40.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:00:40.775+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:00:40.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:40.779+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:00:40.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:00:40.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:00:40.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T10:01:11.174+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:11.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:01:11.175+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:01:11.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:11.178+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:01:11.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:01:11.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:11.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T10:01:41.563+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:41.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:01:41.565+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:01:41.565+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:41.567+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:01:41.567+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:01:41.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:01:41.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T10:02:12.086+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:12.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:02:12.091+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:02:12.091+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:12.106+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:02:12.104+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:02:12.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:12.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.074 seconds
[2024-03-04T10:02:42.614+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:42.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:02:42.616+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:02:42.616+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:42.619+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:02:42.618+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:02:42.620+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:02:42.687+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.076 seconds
[2024-03-04T10:03:13.308+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:13.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:03:13.312+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:03:13.311+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:13.317+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:03:13.315+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:03:13.317+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:13.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.037 seconds
[2024-03-04T10:03:43.768+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:43.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:03:43.770+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:03:43.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:43.773+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:03:43.772+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:03:43.774+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:03:43.793+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T10:04:14.169+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:14.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:04:14.171+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:04:14.171+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:14.173+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:04:14.173+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:04:14.174+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:14.188+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T10:04:44.634+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:44.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:04:44.636+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:04:44.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:44.638+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:04:44.637+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:04:44.638+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:04:44.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-03-04T10:05:15.220+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:15.221+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:05:15.222+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:05:15.222+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:15.227+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:05:15.225+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:05:15.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:15.251+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.034 seconds
[2024-03-04T10:05:45.677+0000] {processor.py:161} INFO - Started process (PID=302) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:45.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:05:45.689+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:05:45.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:45.703+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:05:45.694+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:05:45.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:05:45.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.076 seconds
[2024-03-04T10:06:16.099+0000] {processor.py:161} INFO - Started process (PID=314) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:16.100+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:06:16.102+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:06:16.101+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:16.104+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:06:16.104+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:06:16.104+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:16.116+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-04T10:06:46.469+0000] {processor.py:161} INFO - Started process (PID=326) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:46.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:06:46.471+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:06:46.471+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:46.473+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:06:46.472+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:06:46.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:06:46.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T10:07:17.057+0000] {processor.py:161} INFO - Started process (PID=338) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:17.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:07:17.063+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:07:17.061+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:17.074+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:07:17.073+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:07:17.074+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:17.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.065 seconds
[2024-03-04T10:07:47.561+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:47.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:07:47.563+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:07:47.563+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:47.566+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:07:47.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:07:47.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:07:47.581+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:08:17.959+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:17.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:08:17.961+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:08:17.961+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:17.964+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:08:17.963+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:08:17.964+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:17.978+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T10:08:48.424+0000] {processor.py:161} INFO - Started process (PID=374) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:48.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:08:48.426+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:08:48.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:48.429+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:08:48.428+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:08:48.430+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:08:48.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.036 seconds
[2024-03-04T10:09:18.868+0000] {processor.py:161} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:18.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:09:18.875+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:09:18.872+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:18.895+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:09:18.890+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:09:18.896+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:19.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.138 seconds
[2024-03-04T10:09:49.732+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:49.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:09:49.735+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:09:49.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:49.738+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:09:49.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:09:49.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:09:49.760+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.031 seconds
[2024-03-04T10:10:20.159+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:20.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:10:20.161+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:10:20.161+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:20.163+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:10:20.163+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:10:20.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:20.179+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T10:10:50.638+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:50.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:10:50.640+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:10:50.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:50.643+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:10:50.642+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:10:50.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:10:50.660+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:11:21.191+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:21.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:11:21.193+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:11:21.193+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:21.196+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:11:21.195+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:11:21.196+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:21.213+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:11:51.589+0000] {processor.py:161} INFO - Started process (PID=445) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:51.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:11:51.591+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:11:51.591+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:51.594+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:11:51.593+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:11:51.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:11:51.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-04T10:12:22.033+0000] {processor.py:161} INFO - Started process (PID=457) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:22.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:12:22.045+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:12:22.045+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:22.049+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:12:22.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:12:22.049+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:22.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.045 seconds
[2024-03-04T10:12:52.572+0000] {processor.py:161} INFO - Started process (PID=469) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:52.573+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:12:52.576+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:12:52.575+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:52.579+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:12:52.578+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:12:52.579+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:12:52.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.030 seconds
[2024-03-04T10:13:23.096+0000] {processor.py:161} INFO - Started process (PID=481) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:23.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:13:23.111+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:13:23.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:23.127+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:13:23.126+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:13:23.128+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:23.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.056 seconds
[2024-03-04T10:13:53.569+0000] {processor.py:161} INFO - Started process (PID=493) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:53.570+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:13:53.571+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:13:53.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:53.573+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:13:53.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:13:53.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:13:53.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:14:23.974+0000] {processor.py:161} INFO - Started process (PID=505) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:23.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:14:23.976+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:14:23.976+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:23.980+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:14:23.979+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:14:23.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:24.004+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.032 seconds
[2024-03-04T10:14:54.458+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:54.459+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:14:54.460+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:14:54.460+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:54.463+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:14:54.462+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:14:54.463+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:14:54.530+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.075 seconds
[2024-03-04T10:15:24.892+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:24.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:15:24.894+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:15:24.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:24.896+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:15:24.896+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:15:24.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:24.913+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T10:15:55.364+0000] {processor.py:161} INFO - Started process (PID=541) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:55.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:15:55.366+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:15:55.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:55.368+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:15:55.367+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:15:55.368+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:15:55.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-04T10:16:25.774+0000] {processor.py:161} INFO - Started process (PID=553) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:25.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:16:25.776+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:16:25.776+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:25.779+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:16:25.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:16:25.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:25.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:16:56.236+0000] {processor.py:161} INFO - Started process (PID=565) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:56.237+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:16:56.239+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:16:56.238+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:56.242+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:16:56.242+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:16:56.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:16:56.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-03-04T10:17:26.655+0000] {processor.py:161} INFO - Started process (PID=577) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:26.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:17:26.658+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:17:26.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:26.661+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:17:26.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:17:26.661+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:26.676+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:17:57.053+0000] {processor.py:161} INFO - Started process (PID=589) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:57.054+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:17:57.056+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:17:57.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:57.059+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:17:57.058+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:17:57.059+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:17:57.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:18:27.446+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:27.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:18:27.448+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:18:27.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:27.451+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:18:27.450+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:18:27.451+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:27.466+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-04T10:18:58.010+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:58.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:18:58.012+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:18:58.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:58.014+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:18:58.014+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:18:58.014+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:18:58.027+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-04T10:19:28.595+0000] {processor.py:161} INFO - Started process (PID=625) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:28.596+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:19:28.600+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:19:28.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:28.612+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:19:28.611+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:19:28.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:28.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.038 seconds
[2024-03-04T10:19:59.151+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:59.152+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:19:59.153+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:19:59.153+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:59.157+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:19:59.156+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:19:59.157+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:19:59.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T10:20:29.766+0000] {processor.py:161} INFO - Started process (PID=655) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:20:29.767+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:20:29.768+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:20:29.768+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:20:29.771+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:20:29.770+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:20:29.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:20:29.787+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T10:21:01.101+0000] {processor.py:161} INFO - Started process (PID=667) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:01.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:21:01.117+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:21:01.117+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:01.122+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:21:01.121+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:21:01.123+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:01.157+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.076 seconds
[2024-03-04T10:21:31.642+0000] {processor.py:161} INFO - Started process (PID=679) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:31.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:21:31.644+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:21:31.643+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:31.646+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:21:31.646+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:21:31.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:21:31.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T10:22:02.087+0000] {processor.py:161} INFO - Started process (PID=691) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:02.088+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:22:02.090+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:22:02.089+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:02.092+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:22:02.092+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:22:02.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:02.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-04T10:22:32.306+0000] {processor.py:161} INFO - Started process (PID=703) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:32.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:22:32.308+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:22:32.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:32.311+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:22:32.311+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:22:32.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:22:32.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-03-04T10:23:03.342+0000] {processor.py:161} INFO - Started process (PID=715) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:03.343+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:23:03.344+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:23:03.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:03.347+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:23:03.347+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:23:03.347+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:03.364+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-04T10:23:33.805+0000] {processor.py:161} INFO - Started process (PID=727) to work on /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:33.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-04T10:23:33.807+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:23:33.807+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:33.809+0000] {logging_mixin.py:188} INFO - [2024-03-04T10:23:33.808+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-04T10:23:33.809+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-04T10:23:33.824+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
