[2024-02-25T16:46:57.981+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:46:57.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:46:57.982+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:46:57.981+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:46:57.985+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:46:57.984+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-02-25T16:46:57.985+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:46:57.997+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-02-25T16:47:28.351+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:28.352+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:47:28.353+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:47:28.353+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:28.356+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:47:28.355+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-02-25T16:47:28.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:28.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T16:47:58.707+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:58.709+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:47:58.709+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:47:58.709+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:58.712+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:47:58.711+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 2, in <module>
    from airflow.operators import PythonOperator
ImportError: cannot import name 'PythonOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/__init__.py)
[2024-02-25T16:47:58.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:47:58.728+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T16:48:16.012+0000] {processor.py:161} INFO - Started process (PID=487) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:16.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:48:16.013+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:16.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:16.017+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:16.016+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:48:16.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:16.035+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-02-25T16:48:25.084+0000] {processor.py:161} INFO - Started process (PID=488) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:25.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:48:25.087+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:25.087+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:25.091+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:25.091+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:48:25.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:25.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T16:48:55.460+0000] {processor.py:161} INFO - Started process (PID=499) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:55.461+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:48:55.461+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:55.461+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:55.464+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:48:55.463+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:48:55.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:48:55.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T16:49:25.811+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:25.811+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:49:25.812+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:49:25.812+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:25.814+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:49:25.814+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:49:25.814+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:25.828+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T16:49:56.215+0000] {processor.py:161} INFO - Started process (PID=522) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:56.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:49:56.217+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:49:56.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:56.220+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:49:56.219+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:49:56.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:49:56.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T16:50:26.575+0000] {processor.py:161} INFO - Started process (PID=533) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:26.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:50:26.578+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:50:26.578+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:26.582+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:50:26.581+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:50:26.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:26.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T16:50:56.891+0000] {processor.py:161} INFO - Started process (PID=544) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:56.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:50:56.895+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:50:56.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:56.898+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:50:56.898+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:50:56.898+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:50:56.912+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T16:51:27.280+0000] {processor.py:161} INFO - Started process (PID=555) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:27.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:51:27.282+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:51:27.281+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:27.284+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:51:27.283+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:51:27.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:27.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T16:51:57.681+0000] {processor.py:161} INFO - Started process (PID=566) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:57.683+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:51:57.684+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:51:57.684+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:57.688+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:51:57.687+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:51:57.688+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:51:57.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T16:52:28.050+0000] {processor.py:161} INFO - Started process (PID=577) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:28.052+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:52:28.054+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:52:28.053+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:28.058+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:52:28.057+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:52:28.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:28.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T16:52:58.384+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:58.384+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:52:58.385+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:52:58.385+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:58.387+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:52:58.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:52:58.387+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:52:58.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-02-25T16:53:28.714+0000] {processor.py:161} INFO - Started process (PID=599) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:28.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:53:28.716+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:53:28.716+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:28.719+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:53:28.718+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:53:28.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:28.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T16:53:59.046+0000] {processor.py:161} INFO - Started process (PID=610) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:59.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:53:59.048+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:53:59.048+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:59.052+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:53:59.051+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:53:59.052+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:53:59.070+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T16:54:29.409+0000] {processor.py:161} INFO - Started process (PID=621) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:29.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:54:29.412+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:54:29.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:29.415+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:54:29.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from AIRFLOW_Docker.scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'AIRFLOW_Docker'
[2024-02-25T16:54:29.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:29.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T16:54:53.700+0000] {processor.py:161} INFO - Started process (PID=632) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:53.703+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:54:53.703+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:54:53.703+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:53.707+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:54:53.707+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'scripts.dag_generator'
[2024-02-25T16:54:53.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:54:53.720+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T16:55:24.085+0000] {processor.py:161} INFO - Started process (PID=643) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:24.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:55:24.087+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:24.086+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:24.090+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:24.089+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from scripts.dag_generator import dag_gen
ModuleNotFoundError: No module named 'scripts.dag_generator'
[2024-02-25T16:55:24.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:24.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T16:55:46.207+0000] {processor.py:161} INFO - Started process (PID=650) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:46.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:55:46.210+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.210+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:46.220+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:55:46.328+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.327+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dag_generator_dag
[2024-02-25T16:55:46.338+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.337+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dag_generator_dag
[2024-02-25T16:55:46.345+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.344+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dag_generator_dag
[2024-02-25T16:55:46.345+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.345+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:55:46.354+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.354+0000] {dag.py:3058} INFO - Creating ORM DAG for dag_generator_dag
[2024-02-25T16:55:46.355+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:55:46.354+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:55:46.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.162 seconds
[2024-02-25T16:56:16.495+0000] {processor.py:161} INFO - Started process (PID=661) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:16.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:56:16.497+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:16.497+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:16.504+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:16.526+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:16.526+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:56:16.537+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:16.537+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:56:16.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.063 seconds
[2024-02-25T16:56:46.905+0000] {processor.py:161} INFO - Started process (PID=672) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:46.906+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:56:46.906+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:46.906+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:46.912+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:56:46.927+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:46.927+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:56:46.935+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:56:46.934+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:56:46.948+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.045 seconds
[2024-02-25T16:57:17.309+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:17.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:57:17.313+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:17.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:17.319+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:17.343+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:17.342+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:57:17.356+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:17.355+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:57:17.374+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.068 seconds
[2024-02-25T16:57:47.686+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:47.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:57:47.687+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:47.687+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:47.696+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:57:47.718+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:47.718+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:57:47.729+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:57:47.729+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:57:47.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.060 seconds
[2024-02-25T16:58:18.044+0000] {processor.py:161} INFO - Started process (PID=708) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:18.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:58:18.047+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:18.047+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:18.054+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:18.078+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:18.077+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:58:18.086+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:18.086+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:58:18.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.061 seconds
[2024-02-25T16:58:48.479+0000] {processor.py:161} INFO - Started process (PID=720) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:48.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:58:48.482+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:48.481+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:48.488+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:58:48.510+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:48.510+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:58:48.520+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:58:48.520+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T16:58:48.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.056 seconds
[2024-02-25T16:59:18.866+0000] {processor.py:161} INFO - Started process (PID=733) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:18.868+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:59:18.869+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:18.869+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:18.872+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:18.871+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T16:59:18.872+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:18.887+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T16:59:49.302+0000] {processor.py:161} INFO - Started process (PID=745) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:49.304+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:59:49.305+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:49.304+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:49.308+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:49.307+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T16:59:49.308+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:49.322+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T16:59:57.544+0000] {processor.py:161} INFO - Started process (PID=751) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:57.545+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T16:59:57.546+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:57.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:57.550+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:59:57.549+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T16:59:57.550+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T16:59:57.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T17:00:27.943+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:27.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:00:27.945+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:00:27.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:27.948+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:00:27.947+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:00:27.948+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:27.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T17:00:58.377+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:58.379+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:00:58.380+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:00:58.380+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:58.385+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:00:58.384+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:00:58.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:00:58.405+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.032 seconds
[2024-02-25T17:01:28.773+0000] {processor.py:161} INFO - Started process (PID=788) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:28.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:01:28.775+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:01:28.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:28.778+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:01:28.778+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:01:28.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:28.795+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T17:01:59.181+0000] {processor.py:161} INFO - Started process (PID=800) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:59.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:01:59.182+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:01:59.182+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:59.186+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:01:59.185+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:01:59.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:01:59.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:02:24.551+0000] {processor.py:161} INFO - Started process (PID=812) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:24.554+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:02:24.554+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:02:24.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:24.557+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:02:24.557+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dags.dag_generator import dag_gen
ModuleNotFoundError: No module named 'dags'
[2024-02-25T17:02:24.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:24.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T17:02:54.939+0000] {processor.py:161} INFO - Started process (PID=824) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:54.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:02:54.940+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:02:54.940+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:54.943+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:02:54.942+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dags.dag_generator import dag_gen
ModuleNotFoundError: No module named 'dags'
[2024-02-25T17:02:54.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:02:54.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:03:00.987+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:00.990+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:03:00.990+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:00.990+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:00.995+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:00.995+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:03:00.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:01.010+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T17:03:31.374+0000] {processor.py:161} INFO - Started process (PID=837) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:31.375+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:03:31.375+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:31.375+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:31.382+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:31.466+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:31.466+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T17:03:31.476+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:31.476+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T17:03:31.498+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.126 seconds
[2024-02-25T17:03:48.501+0000] {processor.py:161} INFO - Started process (PID=844) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:48.503+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:03:48.504+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:48.503+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:48.511+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:03:48.522+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:48.521+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T17:03:48.531+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:03:48.531+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T17:03:48.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.048 seconds
[2024-02-25T17:04:18.858+0000] {processor.py:161} INFO - Started process (PID=855) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:18.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:04:18.860+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:04:18.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:18.867+0000] {processor.py:840} INFO - DAG(s) 'dag_generator_dag' retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:18.888+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:04:18.887+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T17:04:18.896+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:04:18.896+0000] {dag.py:3823} INFO - Setting next_dagrun for dag_generator_dag to None, run_after=None
[2024-02-25T17:04:18.910+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.055 seconds
[2024-02-25T17:04:49.216+0000] {processor.py:161} INFO - Started process (PID=866) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:49.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:04:49.218+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:04:49.217+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:49.221+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:04:49.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:04:49.221+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:04:49.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:05:19.596+0000] {processor.py:161} INFO - Started process (PID=877) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:19.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:05:19.598+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:05:19.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:19.601+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:05:19.600+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:05:19.601+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:19.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:05:49.908+0000] {processor.py:161} INFO - Started process (PID=888) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:49.910+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:05:49.910+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:05:49.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:49.913+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:05:49.912+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:05:49.913+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:05:49.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:06:20.246+0000] {processor.py:161} INFO - Started process (PID=899) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:20.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:06:20.248+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:06:20.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:20.251+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:06:20.250+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:06:20.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:20.268+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T17:06:50.527+0000] {processor.py:161} INFO - Started process (PID=910) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:50.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:06:50.530+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:06:50.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:50.532+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:06:50.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:06:50.532+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:06:50.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-02-25T17:07:20.905+0000] {processor.py:161} INFO - Started process (PID=922) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:07:20.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:07:20.908+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:07:20.908+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:07:20.911+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:07:20.910+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ImportError: cannot import name 'dag_gen' from 'dag_generator' (/opt/airflow/dags/dag_generator.py)
[2024-02-25T17:07:20.911+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:07:20.924+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:42:02.967+0000] {processor.py:161} INFO - Started process (PID=1611) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:02.968+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:42:02.968+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:42:02.968+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:02.972+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:42:02.971+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:42:02.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:02.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T17:42:33.314+0000] {processor.py:161} INFO - Started process (PID=1622) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:33.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:42:33.315+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:42:33.315+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:33.318+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:42:33.317+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:42:33.318+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:42:33.331+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-02-25T17:43:03.649+0000] {processor.py:161} INFO - Started process (PID=1633) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:03.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:43:03.651+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:43:03.651+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:03.654+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:43:03.653+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:43:03.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:03.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:43:34.027+0000] {processor.py:161} INFO - Started process (PID=1644) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:34.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:43:34.030+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:43:34.030+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:34.034+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:43:34.033+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:43:34.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:43:34.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T17:44:04.367+0000] {processor.py:161} INFO - Started process (PID=1655) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:04.368+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:44:04.369+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:44:04.368+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:04.372+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:44:04.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:44:04.373+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:04.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:44:34.757+0000] {processor.py:161} INFO - Started process (PID=1666) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:34.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:44:34.759+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:44:34.759+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:34.762+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:44:34.761+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:44:34.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:44:34.778+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:45:05.218+0000] {processor.py:161} INFO - Started process (PID=1677) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:05.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:45:05.220+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:45:05.220+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:05.224+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:45:05.223+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:45:05.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:05.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.042 seconds
[2024-02-25T17:45:35.579+0000] {processor.py:161} INFO - Started process (PID=1688) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:35.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:45:35.581+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:45:35.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:35.584+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:45:35.583+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:45:35.584+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:45:35.600+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T17:46:05.917+0000] {processor.py:161} INFO - Started process (PID=1699) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:05.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:46:05.919+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:46:05.918+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:05.922+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:46:05.921+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:46:05.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:05.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-02-25T17:46:36.274+0000] {processor.py:161} INFO - Started process (PID=1710) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:36.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:46:36.276+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:46:36.276+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:36.278+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:46:36.278+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:46:36.278+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:46:36.292+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:47:06.619+0000] {processor.py:161} INFO - Started process (PID=1721) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:06.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:47:06.622+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:47:06.621+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:06.625+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:47:06.624+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:47:06.625+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:06.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-02-25T17:47:36.947+0000] {processor.py:161} INFO - Started process (PID=1732) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:36.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:47:36.948+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:47:36.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:36.950+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:47:36.950+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:47:36.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:47:36.965+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:48:07.279+0000] {processor.py:161} INFO - Started process (PID=1743) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:07.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:48:07.280+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:48:07.280+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:07.283+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:48:07.283+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:48:07.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:07.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T17:48:37.599+0000] {processor.py:161} INFO - Started process (PID=1754) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:37.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:48:37.600+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:48:37.600+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:37.603+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:48:37.602+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:48:37.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:48:37.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:49:07.951+0000] {processor.py:161} INFO - Started process (PID=1765) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:07.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:49:07.954+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:49:07.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:07.956+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:49:07.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:49:07.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:07.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:49:38.292+0000] {processor.py:161} INFO - Started process (PID=1776) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:38.293+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:49:38.294+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:49:38.294+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:38.296+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:49:38.295+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:49:38.296+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:49:38.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T17:50:08.626+0000] {processor.py:161} INFO - Started process (PID=1787) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:08.627+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:50:08.628+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:50:08.627+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:08.631+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:50:08.630+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:50:08.632+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:08.650+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T17:50:39.009+0000] {processor.py:161} INFO - Started process (PID=1798) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:39.011+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:50:39.012+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:50:39.012+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:39.016+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:50:39.015+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:50:39.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:50:39.031+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T17:51:09.355+0000] {processor.py:161} INFO - Started process (PID=1809) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:09.357+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:51:09.358+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:51:09.358+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:09.361+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:51:09.361+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:51:09.361+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:09.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:51:39.691+0000] {processor.py:161} INFO - Started process (PID=1820) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:39.692+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:51:39.693+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:51:39.692+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:39.695+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:51:39.695+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:51:39.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:51:39.712+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:52:10.057+0000] {processor.py:161} INFO - Started process (PID=1831) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:10.059+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:52:10.060+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:52:10.059+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:10.062+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:52:10.061+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:52:10.062+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:10.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:52:40.425+0000] {processor.py:161} INFO - Started process (PID=1842) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:40.425+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:52:40.426+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:52:40.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:40.429+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:52:40.428+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:52:40.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:52:40.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:53:10.791+0000] {processor.py:161} INFO - Started process (PID=1853) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:10.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:53:10.795+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:53:10.794+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:10.798+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:53:10.798+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:53:10.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:10.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T17:53:41.115+0000] {processor.py:161} INFO - Started process (PID=1864) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:41.117+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:53:41.118+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:53:41.118+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:41.120+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:53:41.120+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:53:41.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:53:41.134+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:54:11.542+0000] {processor.py:161} INFO - Started process (PID=1875) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:11.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:54:11.543+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:54:11.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:11.547+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:54:11.546+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:54:11.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:11.560+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:54:41.893+0000] {processor.py:161} INFO - Started process (PID=1886) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:41.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:54:41.895+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:54:41.894+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:41.897+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:54:41.897+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:54:41.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:54:41.914+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:55:12.246+0000] {processor.py:161} INFO - Started process (PID=1897) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:12.247+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:55:12.248+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:55:12.248+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:12.251+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:55:12.250+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:55:12.251+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:12.264+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:55:42.590+0000] {processor.py:161} INFO - Started process (PID=1908) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:42.592+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:55:42.593+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:55:42.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:42.596+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:55:42.595+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:55:42.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:55:42.612+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-02-25T17:56:12.942+0000] {processor.py:161} INFO - Started process (PID=1919) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:12.944+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:56:12.944+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:56:12.944+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:12.947+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:56:12.946+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:56:12.947+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:12.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T17:56:43.300+0000] {processor.py:161} INFO - Started process (PID=1929) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:43.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:56:43.302+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:56:43.301+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:43.304+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:56:43.304+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:56:43.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:56:43.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T17:57:13.694+0000] {processor.py:161} INFO - Started process (PID=1940) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:13.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:57:13.696+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:57:13.696+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:13.698+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:57:13.698+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:57:13.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:13.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:57:44.031+0000] {processor.py:161} INFO - Started process (PID=1951) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:44.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:57:44.033+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:57:44.033+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:44.036+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:57:44.036+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:57:44.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:57:44.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T17:58:14.360+0000] {processor.py:161} INFO - Started process (PID=1962) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:14.360+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:58:14.361+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:58:14.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:14.364+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:58:14.363+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:58:14.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:14.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:58:44.717+0000] {processor.py:161} INFO - Started process (PID=1973) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:44.719+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:58:44.720+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:58:44.720+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:44.722+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:58:44.722+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:58:44.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:58:44.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:59:15.095+0000] {processor.py:161} INFO - Started process (PID=1984) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:15.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:59:15.097+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:59:15.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:15.100+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:59:15.099+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:59:15.100+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:15.115+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T17:59:45.469+0000] {processor.py:161} INFO - Started process (PID=1995) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:45.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T17:59:45.470+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:59:45.470+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:45.472+0000] {logging_mixin.py:188} INFO - [2024-02-25T17:59:45.472+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T17:59:45.472+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T17:59:45.486+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T18:00:15.723+0000] {processor.py:161} INFO - Started process (PID=2006) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:15.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:00:15.727+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:00:15.726+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:15.731+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:00:15.730+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:00:15.731+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:15.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T18:00:46.056+0000] {processor.py:161} INFO - Started process (PID=2017) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:46.056+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:00:46.057+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:00:46.057+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:46.060+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:00:46.059+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:00:46.061+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:00:46.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:01:16.383+0000] {processor.py:161} INFO - Started process (PID=2028) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:16.386+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:01:16.388+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:01:16.387+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:16.396+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:01:16.394+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:01:16.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:16.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.039 seconds
[2024-02-25T18:01:46.764+0000] {processor.py:161} INFO - Started process (PID=2039) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:46.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:01:46.766+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:01:46.766+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:46.768+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:01:46.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:01:46.768+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:01:46.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:02:17.201+0000] {processor.py:161} INFO - Started process (PID=2050) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:17.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:02:17.204+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:02:17.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:17.206+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:02:17.206+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:02:17.206+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:17.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:02:47.559+0000] {processor.py:161} INFO - Started process (PID=2061) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:47.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:02:47.561+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:02:47.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:47.564+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:02:47.563+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:02:47.564+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:02:47.580+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:03:17.945+0000] {processor.py:161} INFO - Started process (PID=2072) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:17.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:03:17.949+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:03:17.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:17.952+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:03:17.951+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:03:17.952+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:17.967+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:03:48.307+0000] {processor.py:161} INFO - Started process (PID=2083) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:48.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:03:48.308+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:03:48.308+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:48.311+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:03:48.311+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:03:48.312+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:03:48.327+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:04:18.672+0000] {processor.py:161} INFO - Started process (PID=2094) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:18.674+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:04:18.674+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:04:18.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:18.677+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:04:18.676+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:04:18.677+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:18.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:04:49.034+0000] {processor.py:161} INFO - Started process (PID=2105) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:49.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:04:49.035+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:04:49.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:49.038+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:04:49.038+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:04:49.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:04:49.052+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:05:19.381+0000] {processor.py:161} INFO - Started process (PID=2116) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:19.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:05:19.383+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:05:19.383+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:19.386+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:05:19.385+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:05:19.386+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:19.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:05:49.769+0000] {processor.py:161} INFO - Started process (PID=2127) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:49.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:05:49.772+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:05:49.772+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:49.774+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:05:49.774+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:05:49.775+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:05:49.788+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T18:06:20.105+0000] {processor.py:161} INFO - Started process (PID=2137) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:20.107+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:06:20.108+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:06:20.107+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:20.110+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:06:20.110+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:06:20.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:20.124+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:06:50.472+0000] {processor.py:161} INFO - Started process (PID=2148) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:50.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:06:50.474+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:06:50.473+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:50.476+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:06:50.475+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:06:50.476+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:06:50.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:07:20.829+0000] {processor.py:161} INFO - Started process (PID=2159) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:20.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:07:20.832+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:07:20.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:20.835+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:07:20.834+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:07:20.835+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:20.850+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T18:07:51.175+0000] {processor.py:161} INFO - Started process (PID=2170) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:51.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:07:51.177+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:07:51.177+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:51.180+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:07:51.179+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:07:51.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:07:51.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:08:21.514+0000] {processor.py:161} INFO - Started process (PID=2181) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:21.515+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:08:21.515+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:08:21.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:21.518+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:08:21.518+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:08:21.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:21.533+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:08:51.797+0000] {processor.py:161} INFO - Started process (PID=2192) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:51.799+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:08:51.799+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:08:51.799+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:51.803+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:08:51.802+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:08:51.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:08:51.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
[2024-02-25T18:09:22.155+0000] {processor.py:161} INFO - Started process (PID=2203) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:22.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:09:22.157+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:09:22.157+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:22.160+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:09:22.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:09:22.161+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:22.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:09:52.497+0000] {processor.py:161} INFO - Started process (PID=2214) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:52.497+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:09:52.498+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:09:52.498+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:52.500+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:09:52.500+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:09:52.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:09:52.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T18:10:22.821+0000] {processor.py:161} INFO - Started process (PID=2225) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:22.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:10:22.827+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:10:22.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:22.830+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:10:22.829+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:10:22.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:22.845+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T18:10:53.146+0000] {processor.py:161} INFO - Started process (PID=2236) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:53.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:10:53.150+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:10:53.149+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:53.152+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:10:53.152+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:10:53.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:10:53.169+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:11:23.494+0000] {processor.py:161} INFO - Started process (PID=2247) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:23.495+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:11:23.496+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:11:23.496+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:23.498+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:11:23.498+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:11:23.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:23.514+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:11:53.829+0000] {processor.py:161} INFO - Started process (PID=2258) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:53.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:11:53.832+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:11:53.831+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:53.839+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:11:53.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:11:53.840+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:11:53.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.047 seconds
[2024-02-25T18:12:24.736+0000] {processor.py:161} INFO - Started process (PID=2270) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:24.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:12:24.744+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:12:24.743+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:24.753+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:12:24.750+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:12:24.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:24.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.085 seconds
[2024-02-25T18:12:55.290+0000] {processor.py:161} INFO - Started process (PID=2281) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:55.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:12:55.291+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:12:55.291+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:55.294+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:12:55.293+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:12:55.295+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:12:55.309+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:13:25.629+0000] {processor.py:161} INFO - Started process (PID=2292) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:25.630+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:13:25.631+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:13:25.630+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:25.635+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:13:25.634+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:13:25.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:25.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T18:13:55.976+0000] {processor.py:161} INFO - Started process (PID=2303) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:55.978+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:13:55.980+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:13:55.980+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:55.986+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:13:55.985+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:13:55.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:13:56.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.032 seconds
[2024-02-25T18:14:26.322+0000] {processor.py:161} INFO - Started process (PID=2314) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:26.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:14:26.324+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:14:26.323+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:26.327+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:14:26.326+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:14:26.327+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:26.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:14:56.639+0000] {processor.py:161} INFO - Started process (PID=2331) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:56.642+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:14:56.642+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:14:56.642+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:56.646+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:14:56.645+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:14:56.646+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:14:56.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.034 seconds
[2024-02-25T18:15:26.969+0000] {processor.py:161} INFO - Started process (PID=2342) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:26.970+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:15:26.972+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:15:26.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:26.975+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:15:26.974+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:15:26.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:26.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.027 seconds
[2024-02-25T18:15:57.347+0000] {processor.py:161} INFO - Started process (PID=2353) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:57.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:15:57.349+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:15:57.349+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:57.351+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:15:57.351+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:15:57.351+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:15:57.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:16:27.649+0000] {processor.py:161} INFO - Started process (PID=2364) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:27.650+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:16:27.651+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:16:27.650+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:27.654+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:16:27.654+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:16:27.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:27.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T18:16:57.951+0000] {processor.py:161} INFO - Started process (PID=2375) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:57.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:16:57.953+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:16:57.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:57.957+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:16:57.956+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:16:57.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:16:57.977+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-02-25T18:17:28.271+0000] {processor.py:161} INFO - Started process (PID=2386) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:28.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:17:28.273+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:17:28.272+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:28.276+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:17:28.275+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:17:28.276+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:28.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:17:58.570+0000] {processor.py:161} INFO - Started process (PID=2397) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:58.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:17:58.571+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:17:58.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:58.574+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:17:58.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:17:58.574+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:17:58.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:18:28.887+0000] {processor.py:161} INFO - Started process (PID=2408) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:28.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:18:28.888+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:18:28.888+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:28.891+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:18:28.890+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:18:28.891+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:28.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T18:18:59.173+0000] {processor.py:161} INFO - Started process (PID=2419) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:59.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:18:59.175+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:18:59.175+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:59.177+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:18:59.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:18:59.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:18:59.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:19:29.413+0000] {processor.py:161} INFO - Started process (PID=2430) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:29.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:19:29.415+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:19:29.415+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:29.418+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:19:29.417+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:19:29.419+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:29.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T18:19:59.689+0000] {processor.py:161} INFO - Started process (PID=2441) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:59.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:19:59.690+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:19:59.690+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:59.693+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:19:59.692+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:19:59.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:19:59.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:20:30.017+0000] {processor.py:161} INFO - Started process (PID=2452) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:20:30.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:20:30.020+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:20:30.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:20:30.023+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:20:30.022+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:20:30.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:20:30.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T18:21:00.331+0000] {processor.py:161} INFO - Started process (PID=2463) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:00.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:21:00.334+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:21:00.334+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:00.338+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:21:00.337+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:21:00.338+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:00.360+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.031 seconds
[2024-02-25T18:21:30.650+0000] {processor.py:161} INFO - Started process (PID=2474) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:30.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:21:30.652+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:21:30.652+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:30.655+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:21:30.654+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:21:30.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:21:30.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:22:00.959+0000] {processor.py:161} INFO - Started process (PID=2485) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:00.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:22:00.962+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:22:00.962+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:00.966+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:22:00.965+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:22:00.966+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:00.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.030 seconds
[2024-02-25T18:22:31.233+0000] {processor.py:161} INFO - Started process (PID=2496) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:31.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:22:31.234+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:22:31.234+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:31.236+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:22:31.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:22:31.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:22:31.252+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-02-25T18:23:01.513+0000] {processor.py:161} INFO - Started process (PID=2507) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:01.513+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:23:01.514+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:23:01.514+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:01.517+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:23:01.516+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:23:01.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:01.534+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T18:23:31.846+0000] {processor.py:161} INFO - Started process (PID=2518) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:31.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:23:31.847+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:23:31.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:31.850+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:23:31.849+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:23:31.850+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:23:31.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-02-25T18:24:02.195+0000] {processor.py:161} INFO - Started process (PID=2529) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:02.196+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:24:02.197+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:24:02.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:02.200+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:24:02.200+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:24:02.201+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:02.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-02-25T18:24:32.528+0000] {processor.py:161} INFO - Started process (PID=2540) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:32.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:24:32.530+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:24:32.530+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:32.533+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:24:32.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:24:32.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:24:32.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.028 seconds
[2024-02-25T18:25:02.714+0000] {processor.py:161} INFO - Started process (PID=2551) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:02.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:25:02.717+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:25:02.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:02.722+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:25:02.721+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:25:02.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:02.749+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.039 seconds
[2024-02-25T18:25:33.624+0000] {processor.py:161} INFO - Started process (PID=2562) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:33.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:25:33.629+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:25:33.629+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:33.638+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:25:33.635+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:25:33.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:25:33.722+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.107 seconds
[2024-02-25T18:26:04.276+0000] {processor.py:161} INFO - Started process (PID=2573) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:04.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:26:04.280+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:26:04.279+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:04.287+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:26:04.286+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:26:04.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:04.317+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.046 seconds
[2024-02-25T18:26:34.830+0000] {processor.py:161} INFO - Started process (PID=2584) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:34.831+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:26:34.833+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:26:34.832+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:34.838+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:26:34.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:26:34.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:26:34.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T18:27:05.137+0000] {processor.py:161} INFO - Started process (PID=2595) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:05.138+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:27:05.138+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:27:05.138+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:05.141+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:27:05.141+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:27:05.142+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:05.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:27:35.503+0000] {processor.py:161} INFO - Started process (PID=2606) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:35.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:27:35.507+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:27:35.506+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:35.511+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:27:35.510+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:27:35.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:27:35.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.038 seconds
[2024-02-25T18:28:05.826+0000] {processor.py:161} INFO - Started process (PID=2617) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:05.827+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:28:05.827+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:28:05.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:05.830+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:28:05.830+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:28:05.830+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:05.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.025 seconds
[2024-02-25T18:28:36.162+0000] {processor.py:161} INFO - Started process (PID=2628) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:36.164+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:28:36.165+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:28:36.165+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:36.168+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:28:36.167+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:28:36.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:28:36.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.038 seconds
[2024-02-25T18:29:06.474+0000] {processor.py:161} INFO - Started process (PID=2639) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:06.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:29:06.475+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:29:06.475+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:06.479+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:29:06.478+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:29:06.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:06.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-02-25T18:29:36.818+0000] {processor.py:161} INFO - Started process (PID=2650) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:36.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:29:36.821+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:29:36.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:36.824+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:29:36.823+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:29:36.824+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:29:36.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-02-25T18:30:07.173+0000] {processor.py:161} INFO - Started process (PID=2661) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:07.174+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:30:07.174+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:30:07.174+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:07.178+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:30:07.177+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:30:07.178+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:07.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.036 seconds
[2024-02-25T18:30:37.757+0000] {processor.py:161} INFO - Started process (PID=2672) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:37.760+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:30:37.761+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:30:37.761+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:37.766+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:30:37.765+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:30:37.767+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:30:37.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.034 seconds
[2024-02-25T18:31:08.486+0000] {processor.py:161} INFO - Started process (PID=2683) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:08.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:31:08.489+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:31:08.489+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:08.495+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:31:08.493+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:31:08.496+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:08.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.045 seconds
[2024-02-25T18:31:39.148+0000] {processor.py:161} INFO - Started process (PID=2694) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:39.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:31:39.151+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:31:39.151+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:39.157+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:31:39.155+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:31:39.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:31:39.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.044 seconds
[2024-02-25T18:32:09.552+0000] {processor.py:161} INFO - Started process (PID=2705) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:09.553+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:32:09.555+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:32:09.554+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:09.565+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:32:09.562+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:32:09.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:09.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.087 seconds
[2024-02-25T18:32:40.400+0000] {processor.py:161} INFO - Started process (PID=2716) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:40.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:32:40.403+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:32:40.402+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:40.409+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:32:40.407+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:32:40.409+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:32:40.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.041 seconds
[2024-02-25T18:33:10.932+0000] {processor.py:161} INFO - Started process (PID=2727) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:10.935+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:33:10.936+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:33:10.936+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:10.939+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:33:10.938+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:33:10.939+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:10.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-02-25T18:33:41.271+0000] {processor.py:161} INFO - Started process (PID=2738) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:41.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:33:41.273+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:33:41.273+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:41.277+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:33:41.276+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:33:41.277+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:33:41.300+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.032 seconds
[2024-02-25T18:34:11.588+0000] {processor.py:161} INFO - Started process (PID=2749) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:11.590+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:34:11.590+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:34:11.590+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:11.593+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:34:11.592+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:34:11.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:11.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-02-25T18:34:41.950+0000] {processor.py:161} INFO - Started process (PID=2760) to work on /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:41.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-02-25T18:34:41.953+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:34:41.953+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:41.956+0000] {logging_mixin.py:188} INFO - [2024-02-25T18:34:41.955+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-02-25T18:34:41.957+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-02-25T18:34:41.974+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.026 seconds
