[2024-02-25T15:30:12.963+0000] {processor.py:161} INFO - Started process (PID=140) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:30:12.964+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:30:12.965+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:30:12.965+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:30:12.968+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:30:12.967+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 8, in <module>
    default_args=default_args,
NameError: name 'default_args' is not defined
[2024-02-25T15:30:12.968+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:30:12.983+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.022 seconds
[2024-02-25T15:30:43.416+0000] {processor.py:161} INFO - Started process (PID=154) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:30:43.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:30:43.417+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:30:43.417+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:30:43.420+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:30:43.419+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 8, in <module>
    default_args=default_args,
NameError: name 'default_args' is not defined
[2024-02-25T15:30:43.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:30:43.436+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.022 seconds
[2024-02-25T15:31:13.872+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:31:13.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:31:13.875+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:31:13.875+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:31:13.877+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:31:13.876+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 8, in <module>
    default_args=default_args,
NameError: name 'default_args' is not defined
[2024-02-25T15:31:13.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:31:13.893+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.024 seconds
[2024-02-25T15:31:33.256+0000] {processor.py:161} INFO - Started process (PID=183) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:31:33.259+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:31:33.260+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:31:33.259+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:31:33.266+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:31:33.264+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-02-25T15:31:33.266+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:31:33.283+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.029 seconds
[2024-02-25T15:32:03.819+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:32:03.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:32:03.822+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:03.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:03.828+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:03.826+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-02-25T15:32:03.828+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:03.844+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.027 seconds
[2024-02-25T15:32:19.253+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:32:19.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:32:19.255+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:19.255+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:19.262+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:19.260+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 26, in <module>
    send_email(process(extract(220)))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 445, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1159, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 129, in apply_upstream_relationship
    op.set_upstream(operator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): process>, <Task(_PythonDecoratedOperator): extract>]
[2024-02-25T15:32:19.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:19.273+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.022 seconds
[2024-02-25T15:32:49.540+0000] {processor.py:161} INFO - Started process (PID=216) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:32:49.541+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:32:49.542+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:49.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:49.547+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:32:49.546+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 26, in <module>
    send_email(process(extract(220)))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 445, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1159, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 129, in apply_upstream_relationship
    op.set_upstream(operator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): process>, <Task(_PythonDecoratedOperator): extract>]
[2024-02-25T15:32:49.548+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:32:49.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.026 seconds
[2024-02-25T15:33:20.008+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:33:20.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:33:20.010+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:33:20.010+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:33:20.016+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:33:20.015+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/task_3.py", line 26, in <module>
    send_email(process(extract(220)))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 366, in __call__
    op = self.operator_class(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 445, in apply_defaults
    self.set_xcomargs_dependencies()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1159, in set_xcomargs_dependencies
    XComArg.apply_upstream_relationship(self, arg)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom_arg.py", line 129, in apply_upstream_relationship
    op.set_upstream(operator)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 232, in _set_relatives
    raise AirflowException(
airflow.exceptions.AirflowException: Tried to create relationships between tasks that don't have DAGs yet. Set the DAG for at least one task and try again: [<Task(_PythonDecoratedOperator): process>, <Task(_PythonDecoratedOperator): extract>]
[2024-02-25T15:33:20.016+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:33:20.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.023 seconds
[2024-02-25T15:33:43.717+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:33:43.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:33:43.718+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:33:43.718+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:33:43.723+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:33:43.722+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-02-25T15:33:43.723+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:33:43.741+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.026 seconds
[2024-02-25T15:34:14.149+0000] {processor.py:161} INFO - Started process (PID=258) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:34:14.150+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:34:14.151+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:14.150+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:14.156+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:14.155+0000] {dagbag.py:445} ERROR - Failed to bag_dag: /opt/airflow/dags/task_3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 100, in validate
    croniter(self._expression)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 187, in __init__
    self.expanded, self.nth_weekday_of_month = self.expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 811, in expand
    return cls._expand(expr_format, hash_id=hash_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/croniter/croniter.py", line 657, in _expand
    raise CroniterBadCronError(cls.bad_length)
croniter.croniter.CroniterBadCronError: Exactly 5 or 6 columns has to be specified for iterator expression.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 440, in _process_modules
    dag.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 739, in validate
    self.timetable.validate()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 102, in validate
    raise AirflowTimetableInvalid(str(e))
airflow.exceptions.AirflowTimetableInvalid: Exactly 5 or 6 columns has to be specified for iterator expression.
[2024-02-25T15:34:14.156+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:14.173+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.026 seconds
[2024-02-25T15:34:23.420+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:34:23.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:34:23.422+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.421+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:23.429+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:23.494+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.494+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:get_price_task_3
[2024-02-25T15:34:23.504+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.504+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:get_price_task_3
[2024-02-25T15:34:23.511+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.510+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:get_price_task_3
[2024-02-25T15:34:23.511+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.511+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T15:34:23.521+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.520+0000] {dag.py:3058} INFO - Creating ORM DAG for get_price_task_3
[2024-02-25T15:34:23.529+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:23.529+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T15:34:23.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.123 seconds
[2024-02-25T15:34:53.968+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/task_3.py
[2024-02-25T15:34:53.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T15:34:53.969+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:53.969+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:53.975+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T15:34:53.987+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:53.987+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T15:34:54.002+0000] {logging_mixin.py:188} INFO - [2024-02-25T15:34:54.002+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T15:34:54.018+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.054 seconds
[2024-02-25T16:26:56.267+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/task_3.py
[2024-02-25T16:26:56.268+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T16:26:56.270+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:26:56.270+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T16:26:56.280+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T16:26:56.350+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:26:56.349+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:26:56.375+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:26:56.375+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T16:26:56.420+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.156 seconds
[2024-02-25T16:27:26.956+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/task_3.py
[2024-02-25T16:27:26.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T16:27:26.959+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:26.959+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T16:27:26.965+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T16:27:26.978+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:26.978+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:27:26.998+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:26.998+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T16:27:27.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.060 seconds
[2024-02-25T16:27:57.429+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/task_3.py
[2024-02-25T16:27:57.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T16:27:57.432+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:57.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T16:27:57.440+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T16:27:57.454+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:57.454+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:27:57.474+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:27:57.474+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T16:27:57.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.066 seconds
[2024-02-25T16:28:27.910+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/task_3.py
[2024-02-25T16:28:27.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/task_3.py for tasks to queue
[2024-02-25T16:28:27.914+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:28:27.914+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/task_3.py
[2024-02-25T16:28:27.921+0000] {processor.py:840} INFO - DAG(s) 'get_price_task_3' retrieved from /opt/airflow/dags/task_3.py
[2024-02-25T16:28:27.936+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:28:27.936+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2024-02-25T16:28:27.954+0000] {logging_mixin.py:188} INFO - [2024-02-25T16:28:27.954+0000] {dag.py:3823} INFO - Setting next_dagrun for get_price_task_3 to 2024-02-24 00:00:00+00:00, run_after=2024-02-25 00:00:00+00:00
[2024-02-25T16:28:27.968+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/task_3.py took 0.060 seconds
