[2024-03-09T09:59:43.370+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T09:59:43.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T09:59:43.372+0000] {logging_mixin.py:188} INFO - [2024-03-09T09:59:43.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T09:59:43.375+0000] {logging_mixin.py:188} INFO - [2024-03-09T09:59:43.374+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T09:59:43.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T09:59:43.392+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-09T10:00:13.946+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:13.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:00:13.947+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:00:13.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:13.950+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:00:13.949+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:00:13.950+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:13.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-09T10:00:44.323+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:44.324+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:00:44.325+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:00:44.325+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:44.328+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:00:44.327+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:00:44.328+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:00:44.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-09T10:01:14.654+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:14.655+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:01:14.659+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:01:14.658+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:14.662+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:01:14.661+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:01:14.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:14.681+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.029 seconds
[2024-03-09T10:01:45.050+0000] {processor.py:161} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:45.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:01:45.052+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:01:45.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:45.054+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:01:45.053+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:01:45.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:01:45.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-09T10:02:15.440+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:15.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:02:15.442+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:02:15.442+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:15.444+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:02:15.444+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:02:15.444+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:15.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-09T10:02:45.834+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:45.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:02:45.835+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:02:45.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:45.838+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:02:45.837+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:02:45.838+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:02:45.852+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-09T10:03:16.232+0000] {processor.py:161} INFO - Started process (PID=124) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:16.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:03:16.234+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:03:16.233+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:16.236+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:03:16.236+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:03:16.236+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:16.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-09T10:03:46.638+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:46.639+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:03:46.640+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:03:46.640+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:46.643+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:03:46.642+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:03:46.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:03:46.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-09T10:04:17.035+0000] {processor.py:161} INFO - Started process (PID=148) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:17.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:04:17.036+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:04:17.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:17.039+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:04:17.038+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:04:17.039+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:17.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-09T10:04:47.448+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:47.449+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:04:47.450+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:04:47.450+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:47.452+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:04:47.451+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:04:47.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:04:47.465+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-09T10:05:17.811+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:17.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:05:17.813+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:05:17.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:17.816+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:05:17.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:05:17.816+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:17.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-09T10:05:48.214+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:48.215+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:05:48.216+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:05:48.216+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:48.218+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:05:48.218+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:05:48.219+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:05:48.234+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-09T10:06:18.595+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:18.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:06:18.596+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:06:18.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:18.599+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:06:18.598+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:06:18.599+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:18.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.022 seconds
[2024-03-09T10:06:48.968+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:48.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:06:48.971+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:06:48.971+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:48.974+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:06:48.973+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:06:48.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:06:48.990+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.024 seconds
[2024-03-09T10:07:19.363+0000] {processor.py:161} INFO - Started process (PID=220) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:19.363+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:07:19.364+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:07:19.364+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:19.367+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:07:19.366+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:07:19.367+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:19.382+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.021 seconds
[2024-03-09T10:07:49.767+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:49.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:07:49.769+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:07:49.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:49.771+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:07:49.770+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:07:49.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:07:49.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.018 seconds
[2024-03-09T10:08:20.140+0000] {processor.py:161} INFO - Started process (PID=244) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:20.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:08:20.143+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:08:20.142+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:20.146+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:08:20.145+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:08:20.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:20.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.023 seconds
[2024-03-09T10:08:50.529+0000] {processor.py:161} INFO - Started process (PID=256) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:50.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:08:50.531+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:08:50.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:50.533+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:08:50.532+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:08:50.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:08:50.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.019 seconds
[2024-03-09T10:09:20.936+0000] {processor.py:161} INFO - Started process (PID=268) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:09:20.937+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:09:20.938+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:09:20.938+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:09:20.940+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:09:20.940+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:09:20.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:09:20.954+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.020 seconds
[2024-03-09T10:10:25.429+0000] {processor.py:161} INFO - Started process (PID=280) to work on /opt/airflow/dags/dag_gen.py
[2024-03-09T10:10:25.431+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_gen.py for tasks to queue
[2024-03-09T10:10:25.433+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:10:25.433+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:10:25.435+0000] {logging_mixin.py:188} INFO - [2024-03-09T10:10:25.435+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dag_gen.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_gen.py", line 4, in <module>
    from dag_generator import dag_gen
ModuleNotFoundError: No module named 'dag_generator'
[2024-03-09T10:10:25.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_gen.py
[2024-03-09T10:10:25.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_gen.py took 0.030 seconds
